library(ciftiTools)
ciftiTools.setOption('wb_path', '/Applications/workbench/bin_macosxub/wb_command')
devtools::load_all("~/Documents/Github/hrf-z")

# 4-subject MOTOR_LR dev data (BOLD files point to dev/fixtures/hcp_data/)
session_data <- readRDS("dev/fixtures/session_data_4s/session_data_motor_lr_4s.rds")

# --- 1. Canonical HRF (baseline) ---
# Fake a regularize result where every voxel uses the standard canonical HRF.
# fit_workingHRF/multiGLM don't return betas, so this is the cleanest way
# to get canonical GLM betas for comparison.
nV <- 18792
canonical_reg <- list(
  pop_avg = data.frame(
    voxel = 1:nV,
    a1_snapped = rep(6, nV),
    b1_snapped = rep(1, nV),
    c_snapped = rep(1/6, nV)
  ),
  subject_results = NULL
)

result_canonical <- fit_bestHRF(
  canonical_reg,
  BOLD_file = session_data$BOLD_files[1],
  EVs = session_data$EVs_list[[1]],
  nuisance_file = session_data$nuisance_files[1],
  TR = 0.72, onsets = TRUE, offsets = TRUE, verbose = 1
)

# --- 2. Population-adapted HRF ---
# "Slim" = regularize result with best_params_df removed to save space (~2 MB vs ~1 GB).
# Contains: pop_avg, candidate_maps, subject_results, hrf_grid, mask_prop_NA.
# Generated by running regularize_allHRFs on 1125-subject MOTOR_LR data from LaCie.
reg_result <- readRDS("dev/fixtures/regularize_result_motorlr_1125s_slim.rds")
reg_result$subject_results <- NULL  # Force population mode (ignore per-subject candidates)

result_adapted <- fit_bestHRF(
  reg_result,
  BOLD_file = session_data$BOLD_files[1],
  EVs = session_data$EVs_list[[1]],
  nuisance_file = session_data$nuisance_files[1],
  TR = 0.72, onsets = TRUE, offsets = TRUE, verbose = 1
)

# --- 3. Subject-adapted HRF (seffects) ---
# Uses the winning candidate map for subject 1 from regularize.
# NOTE: subject_idx=1 refers to subject 1 in the 1125-subject regularize run,
# NOT necessarily the same person as session_data$BOLD_files[1] (4-subject dev data).
# This is fine for testing the code path but not for real analysis.
reg_subj <- readRDS("dev/fixtures/regularize_result_motorlr_1125s_slim.rds")

result_subject <- fit_bestHRF(
  reg_subj,
  BOLD_file = session_data$BOLD_files[1],
  EVs = session_data$EVs_list[[1]],
  nuisance_file = session_data$nuisance_files[1],
  TR = 0.72, subject_idx = 1,
  onsets = TRUE, offsets = TRUE, verbose = 1
)

# --- Compare all three ---
plot(result_canonical$contrasts$tstat, idx = 1, zlim = c(-8, 8), title = "Canonical HRF - cue t-stat")
plot(result_adapted$contrasts$tstat, idx = 1, zlim = c(-8, 8), title = "Pop Adapted HRF - cue t-stat")
plot(result_subject$contrasts$tstat, idx = 1, zlim = c(-8, 8), title = "Subject Adapted HRF - cue t-stat")

plot(result_canonical$betas, idx = 1, title = "Canonical HRF - cue betas")
plot(result_adapted$betas, idx = 1, title = "Pop Adapted HRF - cue betas")
plot(result_subject$betas, idx = 1, title = "Subject Adapted HRF - cue betas")
