# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

round_regularized_params <- function(results, hrf_params, model = "A", inside_grid = TRUE, max_voxels = -1L) {
    .Call('_hrf_round_regularized_params', PACKAGE = 'hrf', results, hrf_params, model, inside_grid, max_voxels)
}

say_hello <- function() {
    invisible(.Call('_hrf_say_hello', PACKAGE = 'hrf'))
}

